### ISSUE TITLE
Roll back the jitter buffer changes

### ISSUE THREAD

**Issue by pjao** [AndyTaylorTweet/Pi-Star_Binaries#1]
Hi Andy,

Any idea when you will include the roll-backs on jitter buffer?

https://github.com/g4klx/MMDVMHost/commit/bf1773ebcccfc475bb7802a520dabcf10de3e7e0 - Final jitter buffer rollback cleanups. 

https://github.com/g4klx/MMDVMHost/commit/e6ed2e17a13000661296905b49d5517b510bab8b - Roll back the jitter buffer changes. 

Thanks

**Comment by AndyTaylorTweet** [comment]
I'm watching the up-stream closely and waiting for the mass of changes to slow down before pulling in the changes - it won't be long.

**Comment by pjao** [comment]
Thanks Andy, this is very important because like this is almost unusable.

Thanks again!

**Comment by AndyTaylorTweet** [comment]
You are welcome - merged in the new Bins already for you..
