### ISSUE TITLE
Update platformDetect.sh with latest Pi 3 and Pi 4 variants

### ISSUE THREAD

**Issue by victorc-bcgov** [AndyTaylorTweet/Pi-Star_Binaries#10]
platformDetect.sh script in latest Pi-Star software image includes the following revision codes, but these are missing from the GitHub repository:

```
*a22083) raspberryVer="Pi 3 Model B (1GB) - Embest";;
*a02100) raspberryVer="Compute Module 3+ Rev 1.0 (1GB)";;
*a03111) raspberryVer="Pi 4 Model B (1GB) - Sony, UK";;
*b03111) raspberryVer="Pi 4 Model B (2GB) - Sony, UK";;
*c03111) raspberryVer="Pi 4 Model B (4GB) - Sony, UK";;
*b03112) raspberryVer="Pi 4 Model B Rev 1.2 (2GB) - Sony, UK";;
*c03112) raspberryVer="Pi 4 Model B Rev 1.2 (4GB) - Sony, UK";;
```

Please add new revision code for Pi 4 8GB, i.e.

`*d03114) raspberryVer="Pi 4 Model B Rev 1.4 (8GB) - Sony, UK";;`

**Comment by AndyTaylorTweet** [comment]
Added the missing Pi3 models, the older version will not boot on the Pi 4 and the newer v4 train should be used on those.
