### ISSUE TITLE
Update DMRGateway

### ISSUE THREAD

**Issue by sp2ong** [AndyTaylorTweet/Pi-Star_Binaries#9]
It will be nice when to update DMRGateway to latest version where G4KLX add Gateway Dynamic Talk Groups (TGDynRewrite rules)

https://groups.io/g/OpenDV/message/170

> After working with Jon G4TSN with beta versions of this new rewrite rule for the DMR Gateway, it has now been merged into master and available for all to play with. This allows for the use of pseudo reflectors once the existing reflector functionality is removed from BrandMeister. Of course this may be used with other networks too. The new rule looks like:
> 
> TGDynRewrite=2,23500,4000,5000,9,100
> 
> This means that a group of dynamic talk groups can be mapped to a single talk group, along with voice acknowledgements and control over which one is being used. The configuration line means the following:
> 
> The 2 means using slot 2 for all of the following talk groups and private calls.
> The 23500 is the first of the dynamic talk groups, and the 100 at the end is the number of talk groups from that number to use. This maps talk groups 23500 to 23599 in this example. These are triggered by sending a private call to the desired talk group number. This cases a spoken confirmation to be transmitted.
> 4000 is the private call number to disconnect the dynamic talk group. This causes a spoken confirmation to be transmitted.
> 5000 is the private call number to cause the current talk group mapping information to be spoken.
> 9 is the talk group to be used for all communications to the selected dynamic talk group, as well as the voice messages.
> 
> The reason for using private calls is the ability of many radios to have front panel programming so the dynamic talk group numbers can be done manually or programmed on your radio.
> 
> I hope people find this useful. It's possible that more work using the BM API will need to be added externally to the DMR Gateway, but that is an area for other people to investigate.
> 
> Jonathan  G4KLX

**Comment by MW0MWZ** [comment]
Closing this stale issue.
